export const GENERATED_SOCIAL_IMAGE_PATH = '/_yeeet/og.png'

type SocialMetadata = {
  hostname: string
  imageUrl: string
  pageUrl: string
  siteName: string
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function metaTagHasKey(tag: string, key: string) {
  const attributes = /(?:property|name)\s*=\s*(?:["']([^"']+)["']|([^\s>]+))/gi
  for (const match of tag.matchAll(attributes)) {
    if ((match[1] || match[2] || '').toLowerCase() === key) return true
  }
  return false
}

function existingMetaKeys(html: string) {
  const keys = new Set<string>()
  for (const match of html.matchAll(/<meta\b[^>]*>/gi)) {
    for (const key of [
      'og:type',
      'og:site_name',
      'og:title',
      'og:url',
      'og:image',
      'og:image:secure_url',
      'og:image:type',
      'og:image:width',
      'og:image:height',
      'og:image:alt',
      'twitter:card',
      'twitter:title',
      'twitter:image',
      'twitter:image:alt',
    ]) {
      if (metaTagHasKey(match[0], key)) keys.add(key)
    }
  }
  return keys
}

function documentTitle(html: string, fallback: string) {
  const match = /<title\b[^>]*>([\s\S]*?)<\/title\s*>/i.exec(html)
  const title = match?.[1]
    ?.replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  return title || fallback
}

function insertIntoHead(html: string, metadata: string) {
  if (/<\/head\s*>/i.test(html)) {
    return html.replace(/<\/head\s*>/i, `${metadata}</head>`)
  }
  const head = /<head\b[^>]*>/i.exec(html)
  if (head?.index != null) {
    const end = head.index + head[0].length
    return `${html.slice(0, end)}${metadata}${html.slice(end)}`
  }
  const root = /<html\b[^>]*>/i.exec(html)
  if (root?.index != null) {
    const end = root.index + root[0].length
    return `${html.slice(0, end)}<head>${metadata}</head>${html.slice(end)}`
  }
  return `<head>${metadata}</head>${html}`
}

export function injectSiteSocialMetadata(html: string, input: SocialMetadata) {
  const existing = existingMetaKeys(html)
  if (existing.has('og:image') || existing.has('twitter:image')) return html

  const title = documentTitle(html, input.siteName)
  const imageAlt = `${input.siteName} on ${input.hostname}, with its Yeeetling mascot`
  const candidates: Array<[string, string]> = [
    ['og:type', `<meta property="og:type" content="website">`],
    [
      'og:site_name',
      `<meta property="og:site_name" content="${escapeHtml(input.siteName)}">`,
    ],
    ['og:title', `<meta property="og:title" content="${escapeHtml(title)}">`],
    [
      'og:url',
      `<meta property="og:url" content="${escapeHtml(input.pageUrl)}">`,
    ],
    [
      'og:image',
      `<meta property="og:image" content="${escapeHtml(input.imageUrl)}">`,
    ],
    [
      'og:image:secure_url',
      `<meta property="og:image:secure_url" content="${escapeHtml(input.imageUrl)}">`,
    ],
    ['og:image:type', `<meta property="og:image:type" content="image/png">`],
    ['og:image:width', `<meta property="og:image:width" content="1200">`],
    ['og:image:height', `<meta property="og:image:height" content="630">`],
    [
      'og:image:alt',
      `<meta property="og:image:alt" content="${escapeHtml(imageAlt)}">`,
    ],
    [
      'twitter:card',
      `<meta name="twitter:card" content="summary_large_image">`,
    ],
    [
      'twitter:title',
      `<meta name="twitter:title" content="${escapeHtml(title)}">`,
    ],
    [
      'twitter:image',
      `<meta name="twitter:image" content="${escapeHtml(input.imageUrl)}">`,
    ],
    [
      'twitter:image:alt',
      `<meta name="twitter:image:alt" content="${escapeHtml(imageAlt)}">`,
    ],
  ]
  const tags = [
    '<!-- Generated by Yeeet because this site did not provide a social image. -->',
    ...candidates.filter(([key]) => !existing.has(key)).map(([, tag]) => tag),
  ].join('')

  return insertIntoHead(html, tags)
}
