/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MascotRouteImport } from './routes/mascot'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1SitesRouteImport } from './routes/api/v1/sites'
import { Route as ApiV1WebhooksRouteImport } from './routes/api/v1/webhooks'
import { Route as ApiV1AdminIndexRouteImport } from './routes/api/v1/admin/index'
import { Route as ApiV1DeploymentsIndexRouteImport } from './routes/api/v1/deployments/index'
import { Route as ApiV1InvitationsAuthorizeRouteImport } from './routes/api/v1/invitations/authorize'
import { Route as ApiV1SitesSlugRouteImport } from './routes/api/v1/sites/$slug'
import { Route as ApiV1WebhooksWebhookIdRouteImport } from './routes/api/v1/webhooks/$webhookId'
import { Route as ApiV1WebhooksDeliveriesRouteImport } from './routes/api/v1/webhooks/deliveries'
import { Route as ApiV1AdminInvitationsIndexRouteImport } from './routes/api/v1/admin/invitations/index'
import { Route as ApiV1AdminSitesSiteIdRouteImport } from './routes/api/v1/admin/sites/$siteId'
import { Route as ApiV1DeploymentsDeploymentIdCompleteRouteImport } from './routes/api/v1/deployments/$deploymentId/complete'
import { Route as ApiV1SitesSlugAnalyticsRouteImport } from './routes/api/v1/sites/$slug/analytics'
import { Route as ApiV1SitesSlugChannelsRouteImport } from './routes/api/v1/sites/$slug/channels'
import { Route as ApiV1SitesSlugVersionsRouteImport } from './routes/api/v1/sites/$slug/versions'
import { Route as ApiV1AdminInvitationsInvitationIdRevokeRouteImport } from './routes/api/v1/admin/invitations/$invitationId/revoke'
import { Route as ApiV1AdminUsersUserIdBanRouteImport } from './routes/api/v1/admin/users/$userId/ban'
import { Route as ApiV1AdminUsersUserIdRoleRouteImport } from './routes/api/v1/admin/users/$userId/role'
import { Route as ApiV1AdminUsersUserIdUnbanRouteImport } from './routes/api/v1/admin/users/$userId/unban'
import { Route as ApiV1SitesSlugChannelsChannelRouteImport } from './routes/api/v1/sites/$slug/channels/$channel'
import { Route as ApiV1SitesSlugDomainsIndexRouteImport } from './routes/api/v1/sites/$slug/domains/index'
import { Route as ApiV1SitesSlugVersionsDeploymentIdRouteImport } from './routes/api/v1/sites/$slug/versions/$deploymentId'
import { Route as ApiV1SitesSlugDomainsDomainIdIndexRouteImport } from './routes/api/v1/sites/$slug/domains/$domainId/index'
import { Route as ApiV1SitesSlugDomainsDomainIdRefreshRouteImport } from './routes/api/v1/sites/$slug/domains/$domainId/refresh'
import { Route as ApiV1SitesSlugVersionsDeploymentIdAccessRouteImport } from './routes/api/v1/sites/$slug/versions/$deploymentId/access'
import { Route as ApiV1SitesSlugVersionsDeploymentIdActivateRouteImport } from './routes/api/v1/sites/$slug/versions/$deploymentId/activate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MascotRoute = MascotRouteImport.update({
  id: '/mascot',
  path: '/mascot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SitesRoute = ApiV1SitesRouteImport.update({
  id: '/api/v1/sites',
  path: '/api/v1/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhooksRoute = ApiV1WebhooksRouteImport.update({
  id: '/api/v1/webhooks',
  path: '/api/v1/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminIndexRoute = ApiV1AdminIndexRouteImport.update({
  id: '/api/v1/admin/',
  path: '/api/v1/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeploymentsIndexRoute = ApiV1DeploymentsIndexRouteImport.update({
  id: '/api/v1/deployments/',
  path: '/api/v1/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InvitationsAuthorizeRoute =
  ApiV1InvitationsAuthorizeRouteImport.update({
    id: '/api/v1/invitations/authorize',
    path: '/api/v1/invitations/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SitesSlugRoute = ApiV1SitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiV1SitesRoute,
} as any)
const ApiV1WebhooksWebhookIdRoute = ApiV1WebhooksWebhookIdRouteImport.update({
  id: '/$webhookId',
  path: '/$webhookId',
  getParentRoute: () => ApiV1WebhooksRoute,
} as any)
const ApiV1WebhooksDeliveriesRoute = ApiV1WebhooksDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => ApiV1WebhooksRoute,
} as any)
const ApiV1AdminInvitationsIndexRoute =
  ApiV1AdminInvitationsIndexRouteImport.update({
    id: '/api/v1/admin/invitations/',
    path: '/api/v1/admin/invitations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminSitesSiteIdRoute = ApiV1AdminSitesSiteIdRouteImport.update({
  id: '/api/v1/admin/sites/$siteId',
  path: '/api/v1/admin/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeploymentsDeploymentIdCompleteRoute =
  ApiV1DeploymentsDeploymentIdCompleteRouteImport.update({
    id: '/api/v1/deployments/$deploymentId/complete',
    path: '/api/v1/deployments/$deploymentId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SitesSlugAnalyticsRoute = ApiV1SitesSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ApiV1SitesSlugRoute,
} as any)
const ApiV1SitesSlugChannelsRoute = ApiV1SitesSlugChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ApiV1SitesSlugRoute,
} as any)
const ApiV1SitesSlugVersionsRoute = ApiV1SitesSlugVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiV1SitesSlugRoute,
} as any)
const ApiV1AdminInvitationsInvitationIdRevokeRoute =
  ApiV1AdminInvitationsInvitationIdRevokeRouteImport.update({
    id: '/api/v1/admin/invitations/$invitationId/revoke',
    path: '/api/v1/admin/invitations/$invitationId/revoke',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminUsersUserIdBanRoute =
  ApiV1AdminUsersUserIdBanRouteImport.update({
    id: '/api/v1/admin/users/$userId/ban',
    path: '/api/v1/admin/users/$userId/ban',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminUsersUserIdRoleRoute =
  ApiV1AdminUsersUserIdRoleRouteImport.update({
    id: '/api/v1/admin/users/$userId/role',
    path: '/api/v1/admin/users/$userId/role',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminUsersUserIdUnbanRoute =
  ApiV1AdminUsersUserIdUnbanRouteImport.update({
    id: '/api/v1/admin/users/$userId/unban',
    path: '/api/v1/admin/users/$userId/unban',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SitesSlugChannelsChannelRoute =
  ApiV1SitesSlugChannelsChannelRouteImport.update({
    id: '/$channel',
    path: '/$channel',
    getParentRoute: () => ApiV1SitesSlugChannelsRoute,
  } as any)
const ApiV1SitesSlugDomainsIndexRoute =
  ApiV1SitesSlugDomainsIndexRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => ApiV1SitesSlugRoute,
  } as any)
const ApiV1SitesSlugVersionsDeploymentIdRoute =
  ApiV1SitesSlugVersionsDeploymentIdRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => ApiV1SitesSlugVersionsRoute,
  } as any)
const ApiV1SitesSlugDomainsDomainIdIndexRoute =
  ApiV1SitesSlugDomainsDomainIdIndexRouteImport.update({
    id: '/domains/$domainId/',
    path: '/domains/$domainId/',
    getParentRoute: () => ApiV1SitesSlugRoute,
  } as any)
const ApiV1SitesSlugDomainsDomainIdRefreshRoute =
  ApiV1SitesSlugDomainsDomainIdRefreshRouteImport.update({
    id: '/domains/$domainId/refresh',
    path: '/domains/$domainId/refresh',
    getParentRoute: () => ApiV1SitesSlugRoute,
  } as any)
const ApiV1SitesSlugVersionsDeploymentIdAccessRoute =
  ApiV1SitesSlugVersionsDeploymentIdAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => ApiV1SitesSlugVersionsDeploymentIdRoute,
  } as any)
const ApiV1SitesSlugVersionsDeploymentIdActivateRoute =
  ApiV1SitesSlugVersionsDeploymentIdActivateRouteImport.update({
    id: '/activate',
    path: '/activate',
    getParentRoute: () => ApiV1SitesSlugVersionsDeploymentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mascot': typeof MascotRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sites': typeof ApiV1SitesRouteWithChildren
  '/api/v1/webhooks': typeof ApiV1WebhooksRouteWithChildren
  '/api/v1/invitations/authorize': typeof ApiV1InvitationsAuthorizeRoute
  '/api/v1/sites/$slug': typeof ApiV1SitesSlugRouteWithChildren
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/v1/webhooks/deliveries': typeof ApiV1WebhooksDeliveriesRoute
  '/api/v1/admin/': typeof ApiV1AdminIndexRoute
  '/api/v1/deployments/': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/admin/sites/$siteId': typeof ApiV1AdminSitesSiteIdRoute
  '/api/v1/deployments/$deploymentId/complete': typeof ApiV1DeploymentsDeploymentIdCompleteRoute
  '/api/v1/sites/$slug/analytics': typeof ApiV1SitesSlugAnalyticsRoute
  '/api/v1/sites/$slug/channels': typeof ApiV1SitesSlugChannelsRouteWithChildren
  '/api/v1/sites/$slug/versions': typeof ApiV1SitesSlugVersionsRouteWithChildren
  '/api/v1/admin/invitations/': typeof ApiV1AdminInvitationsIndexRoute
  '/api/v1/admin/invitations/$invitationId/revoke': typeof ApiV1AdminInvitationsInvitationIdRevokeRoute
  '/api/v1/admin/users/$userId/ban': typeof ApiV1AdminUsersUserIdBanRoute
  '/api/v1/admin/users/$userId/role': typeof ApiV1AdminUsersUserIdRoleRoute
  '/api/v1/admin/users/$userId/unban': typeof ApiV1AdminUsersUserIdUnbanRoute
  '/api/v1/sites/$slug/channels/$channel': typeof ApiV1SitesSlugChannelsChannelRoute
  '/api/v1/sites/$slug/versions/$deploymentId': typeof ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren
  '/api/v1/sites/$slug/domains/': typeof ApiV1SitesSlugDomainsIndexRoute
  '/api/v1/sites/$slug/domains/$domainId/refresh': typeof ApiV1SitesSlugDomainsDomainIdRefreshRoute
  '/api/v1/sites/$slug/versions/$deploymentId/access': typeof ApiV1SitesSlugVersionsDeploymentIdAccessRoute
  '/api/v1/sites/$slug/versions/$deploymentId/activate': typeof ApiV1SitesSlugVersionsDeploymentIdActivateRoute
  '/api/v1/sites/$slug/domains/$domainId/': typeof ApiV1SitesSlugDomainsDomainIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mascot': typeof MascotRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sites': typeof ApiV1SitesRouteWithChildren
  '/api/v1/webhooks': typeof ApiV1WebhooksRouteWithChildren
  '/api/v1/invitations/authorize': typeof ApiV1InvitationsAuthorizeRoute
  '/api/v1/sites/$slug': typeof ApiV1SitesSlugRouteWithChildren
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/v1/webhooks/deliveries': typeof ApiV1WebhooksDeliveriesRoute
  '/api/v1/admin': typeof ApiV1AdminIndexRoute
  '/api/v1/deployments': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/admin/sites/$siteId': typeof ApiV1AdminSitesSiteIdRoute
  '/api/v1/deployments/$deploymentId/complete': typeof ApiV1DeploymentsDeploymentIdCompleteRoute
  '/api/v1/sites/$slug/analytics': typeof ApiV1SitesSlugAnalyticsRoute
  '/api/v1/sites/$slug/channels': typeof ApiV1SitesSlugChannelsRouteWithChildren
  '/api/v1/sites/$slug/versions': typeof ApiV1SitesSlugVersionsRouteWithChildren
  '/api/v1/admin/invitations': typeof ApiV1AdminInvitationsIndexRoute
  '/api/v1/admin/invitations/$invitationId/revoke': typeof ApiV1AdminInvitationsInvitationIdRevokeRoute
  '/api/v1/admin/users/$userId/ban': typeof ApiV1AdminUsersUserIdBanRoute
  '/api/v1/admin/users/$userId/role': typeof ApiV1AdminUsersUserIdRoleRoute
  '/api/v1/admin/users/$userId/unban': typeof ApiV1AdminUsersUserIdUnbanRoute
  '/api/v1/sites/$slug/channels/$channel': typeof ApiV1SitesSlugChannelsChannelRoute
  '/api/v1/sites/$slug/versions/$deploymentId': typeof ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren
  '/api/v1/sites/$slug/domains': typeof ApiV1SitesSlugDomainsIndexRoute
  '/api/v1/sites/$slug/domains/$domainId/refresh': typeof ApiV1SitesSlugDomainsDomainIdRefreshRoute
  '/api/v1/sites/$slug/versions/$deploymentId/access': typeof ApiV1SitesSlugVersionsDeploymentIdAccessRoute
  '/api/v1/sites/$slug/versions/$deploymentId/activate': typeof ApiV1SitesSlugVersionsDeploymentIdActivateRoute
  '/api/v1/sites/$slug/domains/$domainId': typeof ApiV1SitesSlugDomainsDomainIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mascot': typeof MascotRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sites': typeof ApiV1SitesRouteWithChildren
  '/api/v1/webhooks': typeof ApiV1WebhooksRouteWithChildren
  '/api/v1/invitations/authorize': typeof ApiV1InvitationsAuthorizeRoute
  '/api/v1/sites/$slug': typeof ApiV1SitesSlugRouteWithChildren
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/v1/webhooks/deliveries': typeof ApiV1WebhooksDeliveriesRoute
  '/api/v1/admin/': typeof ApiV1AdminIndexRoute
  '/api/v1/deployments/': typeof ApiV1DeploymentsIndexRoute
  '/api/v1/admin/sites/$siteId': typeof ApiV1AdminSitesSiteIdRoute
  '/api/v1/deployments/$deploymentId/complete': typeof ApiV1DeploymentsDeploymentIdCompleteRoute
  '/api/v1/sites/$slug/analytics': typeof ApiV1SitesSlugAnalyticsRoute
  '/api/v1/sites/$slug/channels': typeof ApiV1SitesSlugChannelsRouteWithChildren
  '/api/v1/sites/$slug/versions': typeof ApiV1SitesSlugVersionsRouteWithChildren
  '/api/v1/admin/invitations/': typeof ApiV1AdminInvitationsIndexRoute
  '/api/v1/admin/invitations/$invitationId/revoke': typeof ApiV1AdminInvitationsInvitationIdRevokeRoute
  '/api/v1/admin/users/$userId/ban': typeof ApiV1AdminUsersUserIdBanRoute
  '/api/v1/admin/users/$userId/role': typeof ApiV1AdminUsersUserIdRoleRoute
  '/api/v1/admin/users/$userId/unban': typeof ApiV1AdminUsersUserIdUnbanRoute
  '/api/v1/sites/$slug/channels/$channel': typeof ApiV1SitesSlugChannelsChannelRoute
  '/api/v1/sites/$slug/versions/$deploymentId': typeof ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren
  '/api/v1/sites/$slug/domains/': typeof ApiV1SitesSlugDomainsIndexRoute
  '/api/v1/sites/$slug/domains/$domainId/refresh': typeof ApiV1SitesSlugDomainsDomainIdRefreshRoute
  '/api/v1/sites/$slug/versions/$deploymentId/access': typeof ApiV1SitesSlugVersionsDeploymentIdAccessRoute
  '/api/v1/sites/$slug/versions/$deploymentId/activate': typeof ApiV1SitesSlugVersionsDeploymentIdActivateRoute
  '/api/v1/sites/$slug/domains/$domainId/': typeof ApiV1SitesSlugDomainsDomainIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/device'
    | '/health'
    | '/login'
    | '/mascot'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/sites'
    | '/api/v1/webhooks'
    | '/api/v1/invitations/authorize'
    | '/api/v1/sites/$slug'
    | '/api/v1/webhooks/$webhookId'
    | '/api/v1/webhooks/deliveries'
    | '/api/v1/admin/'
    | '/api/v1/deployments/'
    | '/api/v1/admin/sites/$siteId'
    | '/api/v1/deployments/$deploymentId/complete'
    | '/api/v1/sites/$slug/analytics'
    | '/api/v1/sites/$slug/channels'
    | '/api/v1/sites/$slug/versions'
    | '/api/v1/admin/invitations/'
    | '/api/v1/admin/invitations/$invitationId/revoke'
    | '/api/v1/admin/users/$userId/ban'
    | '/api/v1/admin/users/$userId/role'
    | '/api/v1/admin/users/$userId/unban'
    | '/api/v1/sites/$slug/channels/$channel'
    | '/api/v1/sites/$slug/versions/$deploymentId'
    | '/api/v1/sites/$slug/domains/'
    | '/api/v1/sites/$slug/domains/$domainId/refresh'
    | '/api/v1/sites/$slug/versions/$deploymentId/access'
    | '/api/v1/sites/$slug/versions/$deploymentId/activate'
    | '/api/v1/sites/$slug/domains/$domainId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/device'
    | '/health'
    | '/login'
    | '/mascot'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/sites'
    | '/api/v1/webhooks'
    | '/api/v1/invitations/authorize'
    | '/api/v1/sites/$slug'
    | '/api/v1/webhooks/$webhookId'
    | '/api/v1/webhooks/deliveries'
    | '/api/v1/admin'
    | '/api/v1/deployments'
    | '/api/v1/admin/sites/$siteId'
    | '/api/v1/deployments/$deploymentId/complete'
    | '/api/v1/sites/$slug/analytics'
    | '/api/v1/sites/$slug/channels'
    | '/api/v1/sites/$slug/versions'
    | '/api/v1/admin/invitations'
    | '/api/v1/admin/invitations/$invitationId/revoke'
    | '/api/v1/admin/users/$userId/ban'
    | '/api/v1/admin/users/$userId/role'
    | '/api/v1/admin/users/$userId/unban'
    | '/api/v1/sites/$slug/channels/$channel'
    | '/api/v1/sites/$slug/versions/$deploymentId'
    | '/api/v1/sites/$slug/domains'
    | '/api/v1/sites/$slug/domains/$domainId/refresh'
    | '/api/v1/sites/$slug/versions/$deploymentId/access'
    | '/api/v1/sites/$slug/versions/$deploymentId/activate'
    | '/api/v1/sites/$slug/domains/$domainId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/device'
    | '/health'
    | '/login'
    | '/mascot'
    | '/api/auth/$'
    | '/api/v1/me'
    | '/api/v1/sites'
    | '/api/v1/webhooks'
    | '/api/v1/invitations/authorize'
    | '/api/v1/sites/$slug'
    | '/api/v1/webhooks/$webhookId'
    | '/api/v1/webhooks/deliveries'
    | '/api/v1/admin/'
    | '/api/v1/deployments/'
    | '/api/v1/admin/sites/$siteId'
    | '/api/v1/deployments/$deploymentId/complete'
    | '/api/v1/sites/$slug/analytics'
    | '/api/v1/sites/$slug/channels'
    | '/api/v1/sites/$slug/versions'
    | '/api/v1/admin/invitations/'
    | '/api/v1/admin/invitations/$invitationId/revoke'
    | '/api/v1/admin/users/$userId/ban'
    | '/api/v1/admin/users/$userId/role'
    | '/api/v1/admin/users/$userId/unban'
    | '/api/v1/sites/$slug/channels/$channel'
    | '/api/v1/sites/$slug/versions/$deploymentId'
    | '/api/v1/sites/$slug/domains/'
    | '/api/v1/sites/$slug/domains/$domainId/refresh'
    | '/api/v1/sites/$slug/versions/$deploymentId/access'
    | '/api/v1/sites/$slug/versions/$deploymentId/activate'
    | '/api/v1/sites/$slug/domains/$domainId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DeviceRoute: typeof DeviceRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  MascotRoute: typeof MascotRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1SitesRoute: typeof ApiV1SitesRouteWithChildren
  ApiV1WebhooksRoute: typeof ApiV1WebhooksRouteWithChildren
  ApiV1InvitationsAuthorizeRoute: typeof ApiV1InvitationsAuthorizeRoute
  ApiV1AdminIndexRoute: typeof ApiV1AdminIndexRoute
  ApiV1DeploymentsIndexRoute: typeof ApiV1DeploymentsIndexRoute
  ApiV1AdminSitesSiteIdRoute: typeof ApiV1AdminSitesSiteIdRoute
  ApiV1DeploymentsDeploymentIdCompleteRoute: typeof ApiV1DeploymentsDeploymentIdCompleteRoute
  ApiV1AdminInvitationsIndexRoute: typeof ApiV1AdminInvitationsIndexRoute
  ApiV1AdminInvitationsInvitationIdRevokeRoute: typeof ApiV1AdminInvitationsInvitationIdRevokeRoute
  ApiV1AdminUsersUserIdBanRoute: typeof ApiV1AdminUsersUserIdBanRoute
  ApiV1AdminUsersUserIdRoleRoute: typeof ApiV1AdminUsersUserIdRoleRoute
  ApiV1AdminUsersUserIdUnbanRoute: typeof ApiV1AdminUsersUserIdUnbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mascot': {
      id: '/mascot'
      path: '/mascot'
      fullPath: '/mascot'
      preLoaderRoute: typeof MascotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sites': {
      id: '/api/v1/sites'
      path: '/api/v1/sites'
      fullPath: '/api/v1/sites'
      preLoaderRoute: typeof ApiV1SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhooks': {
      id: '/api/v1/webhooks'
      path: '/api/v1/webhooks'
      fullPath: '/api/v1/webhooks'
      preLoaderRoute: typeof ApiV1WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/': {
      id: '/api/v1/admin/'
      path: '/api/v1/admin'
      fullPath: '/api/v1/admin/'
      preLoaderRoute: typeof ApiV1AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/': {
      id: '/api/v1/deployments/'
      path: '/api/v1/deployments'
      fullPath: '/api/v1/deployments/'
      preLoaderRoute: typeof ApiV1DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/invitations/authorize': {
      id: '/api/v1/invitations/authorize'
      path: '/api/v1/invitations/authorize'
      fullPath: '/api/v1/invitations/authorize'
      preLoaderRoute: typeof ApiV1InvitationsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sites/$slug': {
      id: '/api/v1/sites/$slug'
      path: '/$slug'
      fullPath: '/api/v1/sites/$slug'
      preLoaderRoute: typeof ApiV1SitesSlugRouteImport
      parentRoute: typeof ApiV1SitesRoute
    }
    '/api/v1/webhooks/$webhookId': {
      id: '/api/v1/webhooks/$webhookId'
      path: '/$webhookId'
      fullPath: '/api/v1/webhooks/$webhookId'
      preLoaderRoute: typeof ApiV1WebhooksWebhookIdRouteImport
      parentRoute: typeof ApiV1WebhooksRoute
    }
    '/api/v1/webhooks/deliveries': {
      id: '/api/v1/webhooks/deliveries'
      path: '/deliveries'
      fullPath: '/api/v1/webhooks/deliveries'
      preLoaderRoute: typeof ApiV1WebhooksDeliveriesRouteImport
      parentRoute: typeof ApiV1WebhooksRoute
    }
    '/api/v1/admin/invitations/': {
      id: '/api/v1/admin/invitations/'
      path: '/api/v1/admin/invitations'
      fullPath: '/api/v1/admin/invitations/'
      preLoaderRoute: typeof ApiV1AdminInvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/sites/$siteId': {
      id: '/api/v1/admin/sites/$siteId'
      path: '/api/v1/admin/sites/$siteId'
      fullPath: '/api/v1/admin/sites/$siteId'
      preLoaderRoute: typeof ApiV1AdminSitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deployments/$deploymentId/complete': {
      id: '/api/v1/deployments/$deploymentId/complete'
      path: '/api/v1/deployments/$deploymentId/complete'
      fullPath: '/api/v1/deployments/$deploymentId/complete'
      preLoaderRoute: typeof ApiV1DeploymentsDeploymentIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sites/$slug/analytics': {
      id: '/api/v1/sites/$slug/analytics'
      path: '/analytics'
      fullPath: '/api/v1/sites/$slug/analytics'
      preLoaderRoute: typeof ApiV1SitesSlugAnalyticsRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/sites/$slug/channels': {
      id: '/api/v1/sites/$slug/channels'
      path: '/channels'
      fullPath: '/api/v1/sites/$slug/channels'
      preLoaderRoute: typeof ApiV1SitesSlugChannelsRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/sites/$slug/versions': {
      id: '/api/v1/sites/$slug/versions'
      path: '/versions'
      fullPath: '/api/v1/sites/$slug/versions'
      preLoaderRoute: typeof ApiV1SitesSlugVersionsRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/admin/invitations/$invitationId/revoke': {
      id: '/api/v1/admin/invitations/$invitationId/revoke'
      path: '/api/v1/admin/invitations/$invitationId/revoke'
      fullPath: '/api/v1/admin/invitations/$invitationId/revoke'
      preLoaderRoute: typeof ApiV1AdminInvitationsInvitationIdRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/users/$userId/ban': {
      id: '/api/v1/admin/users/$userId/ban'
      path: '/api/v1/admin/users/$userId/ban'
      fullPath: '/api/v1/admin/users/$userId/ban'
      preLoaderRoute: typeof ApiV1AdminUsersUserIdBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/users/$userId/role': {
      id: '/api/v1/admin/users/$userId/role'
      path: '/api/v1/admin/users/$userId/role'
      fullPath: '/api/v1/admin/users/$userId/role'
      preLoaderRoute: typeof ApiV1AdminUsersUserIdRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/users/$userId/unban': {
      id: '/api/v1/admin/users/$userId/unban'
      path: '/api/v1/admin/users/$userId/unban'
      fullPath: '/api/v1/admin/users/$userId/unban'
      preLoaderRoute: typeof ApiV1AdminUsersUserIdUnbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sites/$slug/channels/$channel': {
      id: '/api/v1/sites/$slug/channels/$channel'
      path: '/$channel'
      fullPath: '/api/v1/sites/$slug/channels/$channel'
      preLoaderRoute: typeof ApiV1SitesSlugChannelsChannelRouteImport
      parentRoute: typeof ApiV1SitesSlugChannelsRoute
    }
    '/api/v1/sites/$slug/domains/': {
      id: '/api/v1/sites/$slug/domains/'
      path: '/domains'
      fullPath: '/api/v1/sites/$slug/domains/'
      preLoaderRoute: typeof ApiV1SitesSlugDomainsIndexRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/sites/$slug/versions/$deploymentId': {
      id: '/api/v1/sites/$slug/versions/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/api/v1/sites/$slug/versions/$deploymentId'
      preLoaderRoute: typeof ApiV1SitesSlugVersionsDeploymentIdRouteImport
      parentRoute: typeof ApiV1SitesSlugVersionsRoute
    }
    '/api/v1/sites/$slug/domains/$domainId/': {
      id: '/api/v1/sites/$slug/domains/$domainId/'
      path: '/domains/$domainId'
      fullPath: '/api/v1/sites/$slug/domains/$domainId/'
      preLoaderRoute: typeof ApiV1SitesSlugDomainsDomainIdIndexRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/sites/$slug/domains/$domainId/refresh': {
      id: '/api/v1/sites/$slug/domains/$domainId/refresh'
      path: '/domains/$domainId/refresh'
      fullPath: '/api/v1/sites/$slug/domains/$domainId/refresh'
      preLoaderRoute: typeof ApiV1SitesSlugDomainsDomainIdRefreshRouteImport
      parentRoute: typeof ApiV1SitesSlugRoute
    }
    '/api/v1/sites/$slug/versions/$deploymentId/access': {
      id: '/api/v1/sites/$slug/versions/$deploymentId/access'
      path: '/access'
      fullPath: '/api/v1/sites/$slug/versions/$deploymentId/access'
      preLoaderRoute: typeof ApiV1SitesSlugVersionsDeploymentIdAccessRouteImport
      parentRoute: typeof ApiV1SitesSlugVersionsDeploymentIdRoute
    }
    '/api/v1/sites/$slug/versions/$deploymentId/activate': {
      id: '/api/v1/sites/$slug/versions/$deploymentId/activate'
      path: '/activate'
      fullPath: '/api/v1/sites/$slug/versions/$deploymentId/activate'
      preLoaderRoute: typeof ApiV1SitesSlugVersionsDeploymentIdActivateRouteImport
      parentRoute: typeof ApiV1SitesSlugVersionsDeploymentIdRoute
    }
  }
}

interface ApiV1SitesSlugChannelsRouteChildren {
  ApiV1SitesSlugChannelsChannelRoute: typeof ApiV1SitesSlugChannelsChannelRoute
}

const ApiV1SitesSlugChannelsRouteChildren: ApiV1SitesSlugChannelsRouteChildren =
  {
    ApiV1SitesSlugChannelsChannelRoute: ApiV1SitesSlugChannelsChannelRoute,
  }

const ApiV1SitesSlugChannelsRouteWithChildren =
  ApiV1SitesSlugChannelsRoute._addFileChildren(
    ApiV1SitesSlugChannelsRouteChildren,
  )

interface ApiV1SitesSlugVersionsDeploymentIdRouteChildren {
  ApiV1SitesSlugVersionsDeploymentIdAccessRoute: typeof ApiV1SitesSlugVersionsDeploymentIdAccessRoute
  ApiV1SitesSlugVersionsDeploymentIdActivateRoute: typeof ApiV1SitesSlugVersionsDeploymentIdActivateRoute
}

const ApiV1SitesSlugVersionsDeploymentIdRouteChildren: ApiV1SitesSlugVersionsDeploymentIdRouteChildren =
  {
    ApiV1SitesSlugVersionsDeploymentIdAccessRoute:
      ApiV1SitesSlugVersionsDeploymentIdAccessRoute,
    ApiV1SitesSlugVersionsDeploymentIdActivateRoute:
      ApiV1SitesSlugVersionsDeploymentIdActivateRoute,
  }

const ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren =
  ApiV1SitesSlugVersionsDeploymentIdRoute._addFileChildren(
    ApiV1SitesSlugVersionsDeploymentIdRouteChildren,
  )

interface ApiV1SitesSlugVersionsRouteChildren {
  ApiV1SitesSlugVersionsDeploymentIdRoute: typeof ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren
}

const ApiV1SitesSlugVersionsRouteChildren: ApiV1SitesSlugVersionsRouteChildren =
  {
    ApiV1SitesSlugVersionsDeploymentIdRoute:
      ApiV1SitesSlugVersionsDeploymentIdRouteWithChildren,
  }

const ApiV1SitesSlugVersionsRouteWithChildren =
  ApiV1SitesSlugVersionsRoute._addFileChildren(
    ApiV1SitesSlugVersionsRouteChildren,
  )

interface ApiV1SitesSlugRouteChildren {
  ApiV1SitesSlugAnalyticsRoute: typeof ApiV1SitesSlugAnalyticsRoute
  ApiV1SitesSlugChannelsRoute: typeof ApiV1SitesSlugChannelsRouteWithChildren
  ApiV1SitesSlugVersionsRoute: typeof ApiV1SitesSlugVersionsRouteWithChildren
  ApiV1SitesSlugDomainsIndexRoute: typeof ApiV1SitesSlugDomainsIndexRoute
  ApiV1SitesSlugDomainsDomainIdRefreshRoute: typeof ApiV1SitesSlugDomainsDomainIdRefreshRoute
  ApiV1SitesSlugDomainsDomainIdIndexRoute: typeof ApiV1SitesSlugDomainsDomainIdIndexRoute
}

const ApiV1SitesSlugRouteChildren: ApiV1SitesSlugRouteChildren = {
  ApiV1SitesSlugAnalyticsRoute: ApiV1SitesSlugAnalyticsRoute,
  ApiV1SitesSlugChannelsRoute: ApiV1SitesSlugChannelsRouteWithChildren,
  ApiV1SitesSlugVersionsRoute: ApiV1SitesSlugVersionsRouteWithChildren,
  ApiV1SitesSlugDomainsIndexRoute: ApiV1SitesSlugDomainsIndexRoute,
  ApiV1SitesSlugDomainsDomainIdRefreshRoute:
    ApiV1SitesSlugDomainsDomainIdRefreshRoute,
  ApiV1SitesSlugDomainsDomainIdIndexRoute:
    ApiV1SitesSlugDomainsDomainIdIndexRoute,
}

const ApiV1SitesSlugRouteWithChildren = ApiV1SitesSlugRoute._addFileChildren(
  ApiV1SitesSlugRouteChildren,
)

interface ApiV1SitesRouteChildren {
  ApiV1SitesSlugRoute: typeof ApiV1SitesSlugRouteWithChildren
}

const ApiV1SitesRouteChildren: ApiV1SitesRouteChildren = {
  ApiV1SitesSlugRoute: ApiV1SitesSlugRouteWithChildren,
}

const ApiV1SitesRouteWithChildren = ApiV1SitesRoute._addFileChildren(
  ApiV1SitesRouteChildren,
)

interface ApiV1WebhooksRouteChildren {
  ApiV1WebhooksWebhookIdRoute: typeof ApiV1WebhooksWebhookIdRoute
  ApiV1WebhooksDeliveriesRoute: typeof ApiV1WebhooksDeliveriesRoute
}

const ApiV1WebhooksRouteChildren: ApiV1WebhooksRouteChildren = {
  ApiV1WebhooksWebhookIdRoute: ApiV1WebhooksWebhookIdRoute,
  ApiV1WebhooksDeliveriesRoute: ApiV1WebhooksDeliveriesRoute,
}

const ApiV1WebhooksRouteWithChildren = ApiV1WebhooksRoute._addFileChildren(
  ApiV1WebhooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DeviceRoute: DeviceRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MascotRoute: MascotRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1SitesRoute: ApiV1SitesRouteWithChildren,
  ApiV1WebhooksRoute: ApiV1WebhooksRouteWithChildren,
  ApiV1InvitationsAuthorizeRoute: ApiV1InvitationsAuthorizeRoute,
  ApiV1AdminIndexRoute: ApiV1AdminIndexRoute,
  ApiV1DeploymentsIndexRoute: ApiV1DeploymentsIndexRoute,
  ApiV1AdminSitesSiteIdRoute: ApiV1AdminSitesSiteIdRoute,
  ApiV1DeploymentsDeploymentIdCompleteRoute:
    ApiV1DeploymentsDeploymentIdCompleteRoute,
  ApiV1AdminInvitationsIndexRoute: ApiV1AdminInvitationsIndexRoute,
  ApiV1AdminInvitationsInvitationIdRevokeRoute:
    ApiV1AdminInvitationsInvitationIdRevokeRoute,
  ApiV1AdminUsersUserIdBanRoute: ApiV1AdminUsersUserIdBanRoute,
  ApiV1AdminUsersUserIdRoleRoute: ApiV1AdminUsersUserIdRoleRoute,
  ApiV1AdminUsersUserIdUnbanRoute: ApiV1AdminUsersUserIdUnbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
